#!/bin/bash

set -euo pipefail

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/../../hooks_utility.sh"

# perform branch protection
hooks_utility_protect_branch

# Todo use ensure readme edit
# make sure CHANGELOG.md is edited
hooks_utility_ensure_file_modification 'CHANGELOG.md' \
    'merge-binary-finish_feature' \
    'must record CHANGELOG when finish a feature branch'

hooks_utility_ensure_file_modification "CHANGELOG.md" \
    "merge-binary-release" \
    "must record CHANGELOG when publish a new release"
