#!/bin/bash

set -euo pipefail

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/../../hooks_utility.sh"

echo "pre-commit" | hooks_utility_enter

# perform branch protection
hooks_utility_protect_branch

echo "pre-commit" | hooks_utility_pass

exit 0

# Fixme enable

# ensure CHANGELOG is edited
hooks_utility_ensure_changelog_edited "CHANGELOG.md"

# ensure project version number is updated
hooks_utility_ensure_version_updated "hooks_utility.sh" 10

# make sure hooks_utility.sh contains no AM
# Todo need test
if [[ $(get_commit_type_at_pre_commit) == "merge-binary-release" ]]; then
    PATTERN=
    "${PRIMARY_AM_PATTERN}|${SECONDARY_AM_PATTERN}|${TERTIARY_AM_PATTERN}"
    if git diff --cached --no-color | grep -E -q -- "$PATTERN"; then
        exit 1
    fi
fi
